<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>FlowStock.Updater</AssemblyName>
    <RootNamespace>FlowStock.Updater</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\..\img\fs_icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FlowStock.DesktopUpdate\FlowStock.DesktopUpdate.csproj" />
  </ItemGroup>
</Project>
